- name: create user roboshop
  hosts: nginx
  tasks:
  - name: checking roboshop user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: print the output
    ansible.builtin.debug:
     msg: 'Output is: {{output}}'
  - name: print the output
    ansible.builtin.debug:
     msg: 'Output is: {{output.rc}}'
  - name: create user.
    become: true
    ansible.builtin.user:
     name: roboshop
    when: output.rc != 0