- name: create user roboshop
  hosts: localhost
  tasks:
  - name: checking roboshop user exits or not
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true
  - name: printi the output
    ansible.builtin.debug:
     msg: 'Output is: {{output}}'