- name:  Install nginx and run.
  hosts:  nginx
  become:  true
  tasks:
  - name:  Install nginx on node server
    ansible.builtin.yum:
      name: nginx
      state: installed
  - name:  Install nginx on node server
    ansible.builtin.service:
      name: nginx
      state: started
