- name: variables from file
  host: localhost
  vars_files: 
  - variable1.yaml
  tasks:
  - name: taking variables from file
    ansible.builtin.debug
     msg: 'We are learning course: {{Course}} with trainer: {{Trainer}} and the duration is {{Duration}}'